default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: siteweb_dev

test:
  <<: *default
  database: siteweb_test

production:
  <<: *default
  database: siteweb_prod
  username: siteweb
  password: <%= ENV['SITEWEB_DATABASE_PASSWORD'] %>
